In [1]:
import numpy as np
import pandas as pd

## 数据清洗
   - 去除无用列
   - 去除空值
   - 将文本转换为对应数字分类

In [2]:
soldinfo = pd.read_table('soldinfo.txt', sep='\t')
sellinfo = pd.read_table('sellinfo.txt', sep='\t')

'''去除无用的列'''
soldinfo = soldinfo.drop(['unitPrice','schoolInfo', 'framePicUrl', 'titleString', 'resblockName', 'isGarage', 'bizcircleName', 'districtId', 'elevator', 'signTime'], axis=1)
sellinfo = sellinfo.drop(['unitPrice','title', 'layoutImgSrc', 'schoolName', 'address', 'isGarage', 'roomNum', 'regionName', 'districtId', 'communityName', 'communityId', 'ctime'], axis=1)

In [3]:
'''查看每列含有空值的情况'''
soldinfo.isnull().any()

houseCode           False
signPrice           False
listPrice           False
dealCycle           False
houseAreaNum        False
year                 True
buildingType        False
frameOrientation    False
decorationType      False
districtName        False
subwayInfo           True
floorInfo           False
longitude           False
latitude            False
dtype: bool

In [4]:
sellinfo.isnull().any()

houseCode       False
buildingArea    False
buildYear        True
orientation     False
totalFloor      False
decorateType    False
hbtName         False
districtName    False
subwayInfo       True
price           False
longitude       False
latitude        False
dtype: bool

In [5]:
'''删除特定列的空值'''
soldinfo = soldinfo.dropna(subset=['year'])
sellinfo = sellinfo.dropna(subset=['buildYear'])

'''部分列名统一'''
sellinfo.rename(columns={'buildYear':'year', 'hbtName':'buildingType', 'decorateType':'decorationType'}, inplace=True)
soldinfo.rename(columns={'frameOrientation':'orientation'}, inplace=True)

In [6]:
soldinfo.head(5)

houseCode  signPrice  listPrice dealCycle  houseAreaNum    year  \
0  103102446612        338      330.0       489        124.61  2013.0   
1  103105625157        222      230.0        29         89.02  2013.0   
2  103105256418        200      230.0        30         86.71  2013.0   
3  103105570833        197      199.0        25         52.55  1998.0   
4  103103129507        388      400.0        65        148.70  2000.0   

  buildingType orientation decorationType districtName subwayInfo  floorInfo  \
0         板塔结合           西             精装           余杭        NaN  低楼层(共31层)   
1         板塔结合           东             其他           余杭        NaN  低楼层(共16层)   
2         板塔结合           南             简装           余杭        NaN  高楼层(共16层)   
3           板楼           南             简装           西湖        NaN   低楼层(共7层)   
4           板楼           南             其他           西湖        NaN   低楼层(共7层)   

   longitude   latitude  
0  120.12604  30.371922  
1  120.12604  30.371922  
2  120.12604  30.371922  
3  120.10920  30.285497  
4  120.10920  30.285497

In [7]:
sellinfo.head(5)

houseCode  buildingArea    year orientation  totalFloor decorationType  \
0  103106618262         65.70  1989年建           南           6             精装   
1  103104269749         66.68  1989年建           南           6             精装   
2  103106605768         41.09  1989年建           南           6             简装   
3  103106759096         89.00  2012年建           南          25             精装   
4  103106015674         89.51  2012年建           南          26             精装   

  buildingType districtName subwayInfo  price   longitude   latitude  
0           板楼           西湖        NaN  255.0  120.125758  30.297063  
1           板楼           西湖        NaN  243.0  120.125758  30.297063  
2           板楼           西湖        近地铁  169.0  120.125758  30.297063  
3           板楼           西湖        NaN  365.0  120.082526  30.340091  
4           板楼           西湖        近地铁  358.0  120.082526  30.340091

In [8]:
'''将建造年份转换为数字类型'''
import re

year_scaler = lambda x : ''.join(re.findall('\d+', x.__str__()))
soldinfo['year'] = soldinfo['year'].apply(int)
soldinfo['year'] = soldinfo['year'].astype('int16')

sellinfo['year'] = sellinfo['year'].apply(year_scaler)
sellinfo['year'] = sellinfo['year'].astype('int16')

In [9]:
'''处理文本和属性分类'''
orientation_scaler = lambda x:''.join(sorted(list(set(x.replace(' ', '')))))

soldinfo['orientation'] = soldinfo['orientation'].apply(orientation_scaler)
sellinfo['orientation'] = sellinfo['orientation'].apply(orientation_scaler)

In [10]:
'''将文本转化为数字分类'''
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

# sellinfo['orientation'] = encoder.fit_transform(sellinfo[['orientation']])   # 对朝向数据文本进行转换
# sellinfo_ori_col = encoder.classes_   # 获取数字代表的朝向
# soldinfo['orientation'] = encoder.fit_transform(soldinfo[['orientation']])   # 对朝向进行转换
# soldinfo_ori_enc_col = encoder.classes_   # 获取数字代表的朝向

sellinfo = sellinfo[~sellinfo['buildingType'].isin(['暂无数据'])]   # 删除楼房类型数据文本的空值
soldinfo = soldinfo[~soldinfo['buildingType'].isin(['暂无数据'])]

sellinfo['buildingType'] = encoder.fit_transform(sellinfo[['buildingType']])   # 对楼房类型数据文本进行转换
sellinfo_bt_col = encoder.classes_   # 获取数字代表楼房类型
soldinfo['buildingType'] = encoder.fit_transform(soldinfo[['buildingType']])
soldinfo_bt_col = encoder.classes_

sellinfo = sellinfo[~sellinfo['decorationType'].isin(['其他'])]
soldinfo = soldinfo[~soldinfo['decorationType'].isin(['其他'])]

sellinfo['decorationType'] = encoder.fit_transform(sellinfo[['decorationType']])   # 对装修类型数据文本进行转换
sellinfo_dt_co = encoder.classes_   # 获取数字代表装修类型
soldinfo['decorationType'] = encoder.fit_transform(soldinfo[['decorationType']])
soldinfo_dt_co = encoder.classes_

sellinfo['districtName'] = encoder.fit_transform(sellinfo[['districtName']])   # 对所在区域数据文本进行转换
sellinfo_dn_co = encoder.classes_   # 获取区代表装修类型
soldinfo['districtName'] = encoder.fit_transform(soldinfo[['districtName']])
soldinfo_dn_co = encoder.classes_

c:\python\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [11]:
'''转化为独热编码'''
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

sellinfo_ori_hot = encoder.fit_transform(np.array(sellinfo['orientation'].copy()).reshape(-1, 1))
soldinfo_ori_hot = encoder.fit_transform(np.array(soldinfo['orientation'].copy()).reshape(-1, 1))
sellinfo_ori_hot

<9303x15 sparse matrix of type '<class 'numpy.float64'>'
	with 9303 stored elements in Compressed Sparse Row format>

In [12]:
sellinfo['subwayInfo'].value_counts()

近地铁    3896
Name: subwayInfo, dtype: int64

In [13]:
sellinfo[['subwayInfo']] = sellinfo[['subwayInfo']].fillna(0)
sellinfo['subwayInfo'] = sellinfo['subwayInfo'].apply(lambda x:1 if x=='近地铁' else 0)

soldinfo[['subwayInfo']] = soldinfo[['subwayInfo']].fillna(0)
soldinfo['subwayInfo'] = soldinfo['subwayInfo'].apply(lambda x:1 if x=='近地铁' else 0)

In [14]:
soldinfo['floorInfo'] = soldinfo['floorInfo'].apply(lambda x:int(''.join(list(filter(str.isdigit, x)))))

In [15]:
sold_strict_index = soldinfo.districtName.value_counts().index
sell_strict_index = sellinfo.districtName.value_counts().index

# 求售出记录中每个区平均折扣，并用折扣乘以在售数据房价
for i in sold_strict_index:
    sale = sum(soldinfo[soldinfo.districtName == i].signPrice / soldinfo[soldinfo.districtName == i].listPrice) / len(soldinfo[soldinfo.districtName == i])
    sellinfo.loc[(sellinfo.districtName == i), 'price'] = sellinfo[sellinfo.districtName == i].price * sale
    sellinfo['price'] = sellinfo['price'].round(decimals=2)

# 删除无用数据
soldinfo = soldinfo.drop(['listPrice', 'dealCycle'], axis=1)

In [16]:
# 修改列名使两个数据集列名保持一致
sellinfo.rename(columns={'buildingArea':'houseAreaNum'}, inplace=True)
soldinfo.rename(columns={'floorInfo':'totalFloor', 'signPrice':'price'}, inplace=True)

# 修改列的顺序并保持一致
sellinfo = sellinfo[['houseCode','price','houseAreaNum','year','buildingType','orientation','decorationType','districtName','subwayInfo','totalFloor','longitude','latitude']]

In [19]:
# 得到拼接完成的数据
info = pd.concat([sellinfo, soldinfo])

info['houseCode'] = info['houseCode'].apply(lambda x:0 if not str(x).isdigit() else x)
info = info.drop(info[info.houseCode == 0].index)
info.index = range(1, len(info) + 1)

# 转换为整型数据
info['longitude'] = info['longitude'].apply(lambda x:x * 10000)
info['latitude'] = info['latitude'].apply(lambda x:x* 10000)

info['orientation_east'] = 0
info['orientation_west'] = 0
info['orientation_south'] = 0
info['orientation_north'] = 0

for i, j in enumerate(info.orientation):
    if '东' in str(j):
        info.loc[i, 'orientation_east'] = 1
    if '南' in str(j):
        info.loc[i, 'orientation_south'] = 1
    if '西' in str(j):
        info.loc[i, 'orientation_west'] = 1
    if '北' in str(j):
        info.loc[i, 'orientation_north'] = 1

info = info.drop(['orientation'], axis=1)
info = info.dropna()

info = info.astype('int64')

In [20]:
# 数据清洗完成
info

houseCode  price  houseAreaNum  year  buildingType  decorationType  \
1      103106618262    242            65  1989             3               2   
2      103104269749    230            66  1989             3               2   
3      103106605768    160            41  1989             3               1   
4      103106759096    346            89  2012             3               2   
5      103106015674    339            89  2012             3               2   
...             ...    ...           ...   ...           ...             ...   
15414  103106564779    238            84  2011             3               2   
15415  103106077675    143            53  2007             3               2   
15416  103106119385    192            89  2009             3               2   
15417  103105976922    325            82  2011             3               2   
15418  103106510811    168            62  2010             3               1   

       districtName  subwayInfo  totalFloor  longitude  latitude  \
1                10           0           6    1201257    302970   
2                10           0           6    1201257    302970   
3                10           1           6    1201257    302970   
4                10           0          25    1200825    303400   
5                10           1          26    1200825    303400   
...             ...         ...         ...        ...       ...   
15414            10           1          32    1203542    303106   
15415             3           0           6    1202532    303937   
15416             3           0          33    1202774    304056   
15417            10           1          24    1203334    303188   
15418             9           0          18    1200750    303428   

       orientation_east  orientation_west  orientation_south  \
1                     0                 0                  1   
2                     0                 0                  1   
3                     0                 0                  1   
4                     0                 0                  1   
5                     0                 0                  1   
...                 ...               ...                ...   
15414                 1                 1                  0   
15415                 0                 0                  1   
15416                 1                 0                  1   
15417                 0                 0                  1   
15418                 0                 0                  0   

       orientation_north  
1                      0  
2                      0  
3                      0  
4                      0  
5                      0  
...                  ...  
15414                  0  
15415                  0  
15416                  0  
15417                  0  
15418                  0  

[15418 rows x 15 columns]

## 根据每条数据的id的哈希值来区分训练集和测试集
   - test_radio： 区分度
   - id_column： id所在列名
   - 作用：可以防止当有新数据进来时，原顺序不会被打乱

In [21]:
import hashlib

def test_set_check(identifer, test_radio, hash = hashlib.md5):
    return hash(np.int64(identifer)).digest()[-1] < 256 * test_radio  # 返回摘要,作为二进制数据字符串

def split_train_test_by_id(data, test_radio, id_column):
    ids = data[id_column]
    judge_in_test_set = ids.apply(lambda id_:test_set_check(id_, test_radio))
    return data.loc[-judge_in_test_set], data.loc[judge_in_test_set]

In [53]:
train_info, test_info = split_train_test_by_id(info, 0.2, 'houseCode')
train_label = train_info.iloc[:,1]
train_info = train_info.iloc[:,2:]

test_label = test_info.iloc[:,1]
test_info = test_info.iloc[:,2:]

In [54]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_jobs=-1, weights='distance', n_neighbors=1)

In [55]:
house_knn = knn.fit(train_info, train_label)

In [56]:
result = house_knn.predict(test_info)
result

array([242, 398, 187, ..., 295, 180, 159], dtype=int64)

In [57]:
from sklearn.metrics import mean_squared_error

knn_mse = mean_squared_error(test_info.iloc[:, 1], result)
knn_mse = np.sqrt(knn_mse)
knn_mse

1701.7975266473227

In [65]:
knn.predict(np.array([120, 2019, 3, 2, 1,1,33,1201334,303338,1,1,0,1]).reshape(1, -1))

array([327], dtype=int64)

In [79]:
info.subwayInfo.value_counts()

0    8903
1    6515
Name: subwayInfo, dtype: int64

In [73]:
se

array(['上城', '下城', '临安', '余杭', '富阳', '拱墅', '未知区域', '江干', '滨江', '萧山', '西湖',
       '钱塘新区'], dtype=object)

In [60]:
# 对模型进行交叉验证
from sklearn.model_selection import cross_val_score

scores = cross_val_score(knn, train_info, train_label,
                         scoring="neg_mean_squared_error", cv=10)
tree_rmse_scores = np.sqrt(-scores)
tree_rmse_scores

c:\python\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


array([233.01207246, 100.19734459,  74.17775294, 102.64375233,
        67.01645745,  67.41857448,  65.17875863,  59.44608344,
        68.65561989,  80.36510471])

In [61]:
from sklearn.externals import joblib

joblib.dump(house_knn, 'knn.model')

['knn.model']

In [62]:
k = joblib.load('knn.model')

In [63]:
k.predict(test_info)

array([242, 398, 187, ..., 295, 180, 159], dtype=int64)